/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SommelierRouteImport } from './routes/sommelier'
import { Route as RegistrazioneRouteImport } from './routes/registrazione'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventiRouteImport } from './routes/eventi'
import { Route as CantineRouteImport } from './routes/cantine'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SommelierSommelierIdRouteImport } from './routes/sommelier.$sommelierId'
import { Route as CantineCantinaIdRouteImport } from './routes/cantine.$cantinaId'

const SommelierRoute = SommelierRouteImport.update({
  id: '/sommelier',
  path: '/sommelier',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrazioneRoute = RegistrazioneRouteImport.update({
  id: '/registrazione',
  path: '/registrazione',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiRoute = EventiRouteImport.update({
  id: '/eventi',
  path: '/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const CantineRoute = CantineRouteImport.update({
  id: '/cantine',
  path: '/cantine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SommelierSommelierIdRoute = SommelierSommelierIdRouteImport.update({
  id: '/$sommelierId',
  path: '/$sommelierId',
  getParentRoute: () => SommelierRoute,
} as any)
const CantineCantinaIdRoute = CantineCantinaIdRouteImport.update({
  id: '/$cantinaId',
  path: '/$cantinaId',
  getParentRoute: () => CantineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cantine': typeof CantineRouteWithChildren
  '/eventi': typeof EventiRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/registrazione': typeof RegistrazioneRoute
  '/sommelier': typeof SommelierRouteWithChildren
  '/cantine/$cantinaId': typeof CantineCantinaIdRoute
  '/sommelier/$sommelierId': typeof SommelierSommelierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cantine': typeof CantineRouteWithChildren
  '/eventi': typeof EventiRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/registrazione': typeof RegistrazioneRoute
  '/sommelier': typeof SommelierRouteWithChildren
  '/cantine/$cantinaId': typeof CantineCantinaIdRoute
  '/sommelier/$sommelierId': typeof SommelierSommelierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cantine': typeof CantineRouteWithChildren
  '/eventi': typeof EventiRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/registrazione': typeof RegistrazioneRoute
  '/sommelier': typeof SommelierRouteWithChildren
  '/cantine/$cantinaId': typeof CantineCantinaIdRoute
  '/sommelier/$sommelierId': typeof SommelierSommelierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cantine'
    | '/eventi'
    | '/login'
    | '/privacy'
    | '/registrazione'
    | '/sommelier'
    | '/cantine/$cantinaId'
    | '/sommelier/$sommelierId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cantine'
    | '/eventi'
    | '/login'
    | '/privacy'
    | '/registrazione'
    | '/sommelier'
    | '/cantine/$cantinaId'
    | '/sommelier/$sommelierId'
  id:
    | '__root__'
    | '/'
    | '/cantine'
    | '/eventi'
    | '/login'
    | '/privacy'
    | '/registrazione'
    | '/sommelier'
    | '/cantine/$cantinaId'
    | '/sommelier/$sommelierId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CantineRoute: typeof CantineRouteWithChildren
  EventiRoute: typeof EventiRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegistrazioneRoute: typeof RegistrazioneRoute
  SommelierRoute: typeof SommelierRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sommelier': {
      id: '/sommelier'
      path: '/sommelier'
      fullPath: '/sommelier'
      preLoaderRoute: typeof SommelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrazione': {
      id: '/registrazione'
      path: '/registrazione'
      fullPath: '/registrazione'
      preLoaderRoute: typeof RegistrazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi': {
      id: '/eventi'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cantine': {
      id: '/cantine'
      path: '/cantine'
      fullPath: '/cantine'
      preLoaderRoute: typeof CantineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sommelier/$sommelierId': {
      id: '/sommelier/$sommelierId'
      path: '/$sommelierId'
      fullPath: '/sommelier/$sommelierId'
      preLoaderRoute: typeof SommelierSommelierIdRouteImport
      parentRoute: typeof SommelierRoute
    }
    '/cantine/$cantinaId': {
      id: '/cantine/$cantinaId'
      path: '/$cantinaId'
      fullPath: '/cantine/$cantinaId'
      preLoaderRoute: typeof CantineCantinaIdRouteImport
      parentRoute: typeof CantineRoute
    }
  }
}

interface CantineRouteChildren {
  CantineCantinaIdRoute: typeof CantineCantinaIdRoute
}

const CantineRouteChildren: CantineRouteChildren = {
  CantineCantinaIdRoute: CantineCantinaIdRoute,
}

const CantineRouteWithChildren =
  CantineRoute._addFileChildren(CantineRouteChildren)

interface SommelierRouteChildren {
  SommelierSommelierIdRoute: typeof SommelierSommelierIdRoute
}

const SommelierRouteChildren: SommelierRouteChildren = {
  SommelierSommelierIdRoute: SommelierSommelierIdRoute,
}

const SommelierRouteWithChildren = SommelierRoute._addFileChildren(
  SommelierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CantineRoute: CantineRouteWithChildren,
  EventiRoute: EventiRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegistrazioneRoute: RegistrazioneRoute,
  SommelierRoute: SommelierRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
